FROM python:3.11-slim

WORKDIR /app

COPY requirements.lock.txt .
RUN pip install --no-cache-dir -r requirements.lock.txt

COPY . .

CMD ["celery", "-A", "worker.celery_app:celery_app", "beat", "--loglevel=info"]
