"""Initial Crewspan schema migration."""

from __future__ import annotations

from alembic import op
import sqlalchemy as sa
from sqlalchemy import JSON, Boolean, Date, DateTime, Integer, Numeric, String, Text
from sqlalchemy.dialects import postgresql
from sqlalchemy.dialects.postgresql import UUID

revision = "001_initial"
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    op.create_table(
        "tenants",
        sa.Column("id", postgresql.UUID(as_uuid=True), primary_key=True),
        sa.Column("slug", String(64), nullable=False, index=True, unique=True),
        sa.Column("display_name", String(255), nullable=False),
        sa.Column("legal_name", String(255), nullable=True),
        sa.Column("subscription_tier", String(32), nullable=False),
        sa.Column("timezone", String(64), nullable=False),
        sa.Column("is_active", Boolean, nullable=False),
        sa.Column("feature_flags", JSON, nullable=True),
        sa.Column("settings", JSON, nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("deleted_at", sa.DateTime(timezone=True), nullable=True, index=True),
    )
    op.create_table(
        "users",
        sa.Column("id", postgresql.UUID(as_uuid=True), primary_key=True),
        sa.Column("tenant_id", postgresql.UUID(as_uuid=True), nullable=False, index=True),
        sa.Column("email", String(320), nullable=False, index=True, unique=True),
        sa.Column("full_name", String(255), nullable=False),
        sa.Column("password_hash", String(255), nullable=False),
        sa.Column("phone", String(32), nullable=True),
        sa.Column("role_id", UUID(as_uuid=True), nullable=False, index=True),
        sa.Column("is_active", Boolean, nullable=False),
        sa.Column("last_login_at", DateTime(timezone=True), nullable=True),
        sa.Column("preferences", JSON, nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("deleted_at", sa.DateTime(timezone=True), nullable=True, index=True),
    )
    op.create_table(
        "roles",
        sa.Column("id", postgresql.UUID(as_uuid=True), primary_key=True),
        sa.Column("tenant_id", postgresql.UUID(as_uuid=True), nullable=False, index=True),
        sa.Column("name", String(128), nullable=False, index=True),
        sa.Column("description", Text, nullable=True),
        sa.Column("permissions", JSON, nullable=False),
        sa.Column("is_system", Boolean, nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("deleted_at", sa.DateTime(timezone=True), nullable=True, index=True),
    )
    op.create_table(
        "customers",
        sa.Column("id", postgresql.UUID(as_uuid=True), primary_key=True),
        sa.Column("tenant_id", postgresql.UUID(as_uuid=True), nullable=False, index=True),
        sa.Column("account_number", String(64), nullable=False, index=True),
        sa.Column("name", String(255), nullable=False, index=True),
        sa.Column("customer_type", String(32), nullable=False),
        sa.Column("billing_email", String(320), nullable=True),
        sa.Column("billing_address", JSON, nullable=True),
        sa.Column("credit_limit", Numeric(14, 2), nullable=True),
        sa.Column("payment_terms_days", Integer, nullable=False),
        sa.Column("notes", Text, nullable=True),
        sa.Column("is_active", Boolean, nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("deleted_at", sa.DateTime(timezone=True), nullable=True, index=True),
    )
    op.create_table(
        "customer_sites",
        sa.Column("id", postgresql.UUID(as_uuid=True), primary_key=True),
        sa.Column("tenant_id", postgresql.UUID(as_uuid=True), nullable=False, index=True),
        sa.Column("customer_id", UUID(as_uuid=True), nullable=False, index=True),
        sa.Column("site_code", String(64), nullable=False, index=True),
        sa.Column("name", String(255), nullable=False),
        sa.Column("address", JSON, nullable=False),
        sa.Column("latitude", Numeric(10, 7), nullable=True),
        sa.Column("longitude", Numeric(10, 7), nullable=True),
        sa.Column("access_instructions", Text, nullable=True),
        sa.Column("service_window", JSON, nullable=True),
        sa.Column("is_active", Boolean, nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("deleted_at", sa.DateTime(timezone=True), nullable=True, index=True),
    )
    op.create_table(
        "contacts",
        sa.Column("id", postgresql.UUID(as_uuid=True), primary_key=True),
        sa.Column("tenant_id", postgresql.UUID(as_uuid=True), nullable=False, index=True),
        sa.Column("customer_id", UUID(as_uuid=True), nullable=False, index=True),
        sa.Column("site_id", UUID(as_uuid=True), nullable=True, index=True),
        sa.Column("first_name", String(128), nullable=False),
        sa.Column("last_name", String(128), nullable=False),
        sa.Column("email", String(320), nullable=True),
        sa.Column("phone", String(32), nullable=True),
        sa.Column("role_title", String(128), nullable=True),
        sa.Column("is_primary", Boolean, nullable=False),
        sa.Column("notify_on_dispatch", Boolean, nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("deleted_at", sa.DateTime(timezone=True), nullable=True, index=True),
    )
    op.create_table(
        "work_orders",
        sa.Column("id", postgresql.UUID(as_uuid=True), primary_key=True),
        sa.Column("tenant_id", postgresql.UUID(as_uuid=True), nullable=False, index=True),
        sa.Column("order_number", String(64), nullable=False, index=True, unique=True),
        sa.Column("customer_id", UUID(as_uuid=True), nullable=False, index=True),
        sa.Column("site_id", UUID(as_uuid=True), nullable=False, index=True),
        sa.Column("title", String(255), nullable=False),
        sa.Column("description", Text, nullable=True),
        sa.Column("priority", String(16), nullable=False),
        sa.Column("status", String(32), nullable=False, index=True),
        sa.Column("scheduled_start", DateTime(timezone=True), nullable=True),
        sa.Column("scheduled_end", DateTime(timezone=True), nullable=True),
        sa.Column("assigned_technician_id", UUID(as_uuid=True), nullable=True, index=True),
        sa.Column("sla_policy_id", UUID(as_uuid=True), nullable=True),
        sa.Column("estimated_duration_minutes", Integer, nullable=True),
        sa.Column("completion_notes", Text, nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("deleted_at", sa.DateTime(timezone=True), nullable=True, index=True),
    )
    op.create_table(
        "work_order_tasks",
        sa.Column("id", postgresql.UUID(as_uuid=True), primary_key=True),
        sa.Column("tenant_id", postgresql.UUID(as_uuid=True), nullable=False, index=True),
        sa.Column("work_order_id", UUID(as_uuid=True), nullable=False, index=True),
        sa.Column("sequence", Integer, nullable=False),
        sa.Column("title", String(255), nullable=False),
        sa.Column("instructions", Text, nullable=True),
        sa.Column("is_required", Boolean, nullable=False),
        sa.Column("status", String(32), nullable=False),
        sa.Column("completed_at", DateTime(timezone=True), nullable=True),
        sa.Column("completed_by_id", UUID(as_uuid=True), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("deleted_at", sa.DateTime(timezone=True), nullable=True, index=True),
    )
    op.create_table(
        "technicians",
        sa.Column("id", postgresql.UUID(as_uuid=True), primary_key=True),
        sa.Column("tenant_id", postgresql.UUID(as_uuid=True), nullable=False, index=True),
        sa.Column("user_id", UUID(as_uuid=True), nullable=False, index=True, unique=True),
        sa.Column("employee_id", String(64), nullable=False, index=True),
        sa.Column("home_base_latitude", Numeric(10, 7), nullable=True),
        sa.Column("home_base_longitude", Numeric(10, 7), nullable=True),
        sa.Column("max_daily_hours", Integer, nullable=False),
        sa.Column("status", String(32), nullable=False, index=True),
        sa.Column("certifications", JSON, nullable=True),
        sa.Column("vehicle_info", JSON, nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("deleted_at", sa.DateTime(timezone=True), nullable=True, index=True),
    )
    op.create_table(
        "technician_skills",
        sa.Column("id", postgresql.UUID(as_uuid=True), primary_key=True),
        sa.Column("tenant_id", postgresql.UUID(as_uuid=True), nullable=False, index=True),
        sa.Column("technician_id", UUID(as_uuid=True), nullable=False, index=True),
        sa.Column("skill_code", String(64), nullable=False, index=True),
        sa.Column("skill_name", String(128), nullable=False),
        sa.Column("proficiency_level", Integer, nullable=False),
        sa.Column("certified_at", Date, nullable=True),
        sa.Column("expires_at", Date, nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("deleted_at", sa.DateTime(timezone=True), nullable=True, index=True),
    )
    op.create_table(
        "schedules",
        sa.Column("id", postgresql.UUID(as_uuid=True), primary_key=True),
        sa.Column("tenant_id", postgresql.UUID(as_uuid=True), nullable=False, index=True),
        sa.Column("technician_id", UUID(as_uuid=True), nullable=False, index=True),
        sa.Column("work_order_id", UUID(as_uuid=True), nullable=True, index=True),
        sa.Column("event_type", String(32), nullable=False),
        sa.Column("starts_at", DateTime(timezone=True), nullable=False, index=True),
        sa.Column("ends_at", DateTime(timezone=True), nullable=False),
        sa.Column("title", String(255), nullable=False),
        sa.Column("notes", Text, nullable=True),
        sa.Column("is_locked", Boolean, nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("deleted_at", sa.DateTime(timezone=True), nullable=True, index=True),
    )
    op.create_table(
        "dispatches",
        sa.Column("id", postgresql.UUID(as_uuid=True), primary_key=True),
        sa.Column("tenant_id", postgresql.UUID(as_uuid=True), nullable=False, index=True),
        sa.Column("work_order_id", UUID(as_uuid=True), nullable=False, index=True),
        sa.Column("technician_id", UUID(as_uuid=True), nullable=False, index=True),
        sa.Column("dispatched_at", DateTime(timezone=True), nullable=False),
        sa.Column("accepted_at", DateTime(timezone=True), nullable=True),
        sa.Column("status", String(32), nullable=False, index=True),
        sa.Column("dispatch_notes", Text, nullable=True),
        sa.Column("route_eta_minutes", Integer, nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("deleted_at", sa.DateTime(timezone=True), nullable=True, index=True),
    )
    op.create_table(
        "inventory_items",
        sa.Column("id", postgresql.UUID(as_uuid=True), primary_key=True),
        sa.Column("tenant_id", postgresql.UUID(as_uuid=True), nullable=False, index=True),
        sa.Column("sku", String(64), nullable=False, index=True, unique=True),
        sa.Column("name", String(255), nullable=False, index=True),
        sa.Column("description", Text, nullable=True),
        sa.Column("unit_of_measure", String(16), nullable=False),
        sa.Column("unit_cost", Numeric(14, 4), nullable=False),
        sa.Column("reorder_point", Integer, nullable=False),
        sa.Column("reorder_quantity", Integer, nullable=False),
        sa.Column("is_active", Boolean, nullable=False),
        sa.Column("category", String(64), nullable=True, index=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("deleted_at", sa.DateTime(timezone=True), nullable=True, index=True),
    )
    op.create_table(
        "inventory_locations",
        sa.Column("id", postgresql.UUID(as_uuid=True), primary_key=True),
        sa.Column("tenant_id", postgresql.UUID(as_uuid=True), nullable=False, index=True),
        sa.Column("code", String(64), nullable=False, index=True),
        sa.Column("name", String(255), nullable=False),
        sa.Column("location_type", String(32), nullable=False),
        sa.Column("technician_id", UUID(as_uuid=True), nullable=True, index=True),
        sa.Column("address", JSON, nullable=True),
        sa.Column("is_active", Boolean, nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("deleted_at", sa.DateTime(timezone=True), nullable=True, index=True),
    )
    op.create_table(
        "stock_movements",
        sa.Column("id", postgresql.UUID(as_uuid=True), primary_key=True),
        sa.Column("tenant_id", postgresql.UUID(as_uuid=True), nullable=False, index=True),
        sa.Column("item_id", UUID(as_uuid=True), nullable=False, index=True),
        sa.Column("from_location_id", UUID(as_uuid=True), nullable=True, index=True),
        sa.Column("to_location_id", UUID(as_uuid=True), nullable=True, index=True),
        sa.Column("quantity", Numeric(14, 4), nullable=False),
        sa.Column("movement_type", String(32), nullable=False, index=True),
        sa.Column("reference_type", String(64), nullable=True),
        sa.Column("reference_id", UUID(as_uuid=True), nullable=True),
        sa.Column("performed_by_id", UUID(as_uuid=True), nullable=True),
        sa.Column("notes", Text, nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("deleted_at", sa.DateTime(timezone=True), nullable=True, index=True),
    )
    op.create_table(
        "parts_requests",
        sa.Column("id", postgresql.UUID(as_uuid=True), primary_key=True),
        sa.Column("tenant_id", postgresql.UUID(as_uuid=True), nullable=False, index=True),
        sa.Column("work_order_id", UUID(as_uuid=True), nullable=False, index=True),
        sa.Column("requested_by_id", UUID(as_uuid=True), nullable=False, index=True),
        sa.Column("status", String(32), nullable=False, index=True),
        sa.Column("needed_by", DateTime(timezone=True), nullable=True),
        sa.Column("fulfillment_location_id", UUID(as_uuid=True), nullable=True),
        sa.Column("line_items", JSON, nullable=False),
        sa.Column("notes", Text, nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("deleted_at", sa.DateTime(timezone=True), nullable=True, index=True),
    )
    op.create_table(
        "invoices",
        sa.Column("id", postgresql.UUID(as_uuid=True), primary_key=True),
        sa.Column("tenant_id", postgresql.UUID(as_uuid=True), nullable=False, index=True),
        sa.Column("invoice_number", String(64), nullable=False, index=True, unique=True),
        sa.Column("customer_id", UUID(as_uuid=True), nullable=False, index=True),
        sa.Column("work_order_id", UUID(as_uuid=True), nullable=True, index=True),
        sa.Column("status", String(32), nullable=False, index=True),
        sa.Column("issue_date", Date, nullable=False),
        sa.Column("due_date", Date, nullable=False),
        sa.Column("subtotal", Numeric(14, 2), nullable=False),
        sa.Column("tax_amount", Numeric(14, 2), nullable=False),
        sa.Column("total_amount", Numeric(14, 2), nullable=False),
        sa.Column("currency", String(3), nullable=False),
        sa.Column("notes", Text, nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("deleted_at", sa.DateTime(timezone=True), nullable=True, index=True),
    )
    op.create_table(
        "invoice_line_items",
        sa.Column("id", postgresql.UUID(as_uuid=True), primary_key=True),
        sa.Column("tenant_id", postgresql.UUID(as_uuid=True), nullable=False, index=True),
        sa.Column("invoice_id", UUID(as_uuid=True), nullable=False, index=True),
        sa.Column("description", String(512), nullable=False),
        sa.Column("quantity", Numeric(14, 4), nullable=False),
        sa.Column("unit_price", Numeric(14, 4), nullable=False),
        sa.Column("tax_rate", Numeric(6, 4), nullable=False),
        sa.Column("line_total", Numeric(14, 2), nullable=False),
        sa.Column("item_type", String(32), nullable=False),
        sa.Column("reference_id", UUID(as_uuid=True), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("deleted_at", sa.DateTime(timezone=True), nullable=True, index=True),
    )
    op.create_table(
        "payments",
        sa.Column("id", postgresql.UUID(as_uuid=True), primary_key=True),
        sa.Column("tenant_id", postgresql.UUID(as_uuid=True), nullable=False, index=True),
        sa.Column("invoice_id", UUID(as_uuid=True), nullable=False, index=True),
        sa.Column("amount", Numeric(14, 2), nullable=False),
        sa.Column("payment_method", String(32), nullable=False),
        sa.Column("payment_date", Date, nullable=False),
        sa.Column("reference_number", String(128), nullable=True),
        sa.Column("status", String(32), nullable=False),
        sa.Column("processor_response", JSON, nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("deleted_at", sa.DateTime(timezone=True), nullable=True, index=True),
    )
    op.create_table(
        "sla_policies",
        sa.Column("id", postgresql.UUID(as_uuid=True), primary_key=True),
        sa.Column("tenant_id", postgresql.UUID(as_uuid=True), nullable=False, index=True),
        sa.Column("name", String(128), nullable=False, index=True),
        sa.Column("description", Text, nullable=True),
        sa.Column("priority", String(16), nullable=False, index=True),
        sa.Column("response_minutes", Integer, nullable=False),
        sa.Column("resolution_minutes", Integer, nullable=False),
        sa.Column("business_hours_only", Boolean, nullable=False),
        sa.Column("escalation_rules", JSON, nullable=True),
        sa.Column("is_active", Boolean, nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("deleted_at", sa.DateTime(timezone=True), nullable=True, index=True),
    )
    op.create_table(
        "sla_breaches",
        sa.Column("id", postgresql.UUID(as_uuid=True), primary_key=True),
        sa.Column("tenant_id", postgresql.UUID(as_uuid=True), nullable=False, index=True),
        sa.Column("work_order_id", UUID(as_uuid=True), nullable=False, index=True),
        sa.Column("sla_policy_id", UUID(as_uuid=True), nullable=False, index=True),
        sa.Column("breach_type", String(32), nullable=False, index=True),
        sa.Column("expected_at", DateTime(timezone=True), nullable=False),
        sa.Column("detected_at", DateTime(timezone=True), nullable=False),
        sa.Column("minutes_overdue", Integer, nullable=False),
        sa.Column("acknowledged", Boolean, nullable=False),
        sa.Column("escalation_level", Integer, nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("deleted_at", sa.DateTime(timezone=True), nullable=True, index=True),
    )
    op.create_table(
        "service_contracts",
        sa.Column("id", postgresql.UUID(as_uuid=True), primary_key=True),
        sa.Column("tenant_id", postgresql.UUID(as_uuid=True), nullable=False, index=True),
        sa.Column("customer_id", UUID(as_uuid=True), nullable=False, index=True),
        sa.Column("contract_number", String(64), nullable=False, index=True, unique=True),
        sa.Column("name", String(255), nullable=False),
        sa.Column("start_date", Date, nullable=False),
        sa.Column("end_date", Date, nullable=True),
        sa.Column("billing_frequency", String(32), nullable=False),
        sa.Column("annual_value", Numeric(14, 2), nullable=True),
        sa.Column("covered_sites", JSON, nullable=True),
        sa.Column("terms", JSON, nullable=True),
        sa.Column("status", String(32), nullable=False, index=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("deleted_at", sa.DateTime(timezone=True), nullable=True, index=True),
    )
    op.create_table(
        "equipment",
        sa.Column("id", postgresql.UUID(as_uuid=True), primary_key=True),
        sa.Column("tenant_id", postgresql.UUID(as_uuid=True), nullable=False, index=True),
        sa.Column("customer_id", UUID(as_uuid=True), nullable=False, index=True),
        sa.Column("site_id", UUID(as_uuid=True), nullable=True, index=True),
        sa.Column("asset_tag", String(64), nullable=False, index=True),
        sa.Column("name", String(255), nullable=False),
        sa.Column("manufacturer", String(128), nullable=True),
        sa.Column("model_number", String(128), nullable=True),
        sa.Column("serial_number", String(128), nullable=True, index=True),
        sa.Column("install_date", Date, nullable=True),
        sa.Column("warranty_expires", Date, nullable=True),
        sa.Column("specifications", JSON, nullable=True),
        sa.Column("status", String(32), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("deleted_at", sa.DateTime(timezone=True), nullable=True, index=True),
    )
    op.create_table(
        "notifications",
        sa.Column("id", postgresql.UUID(as_uuid=True), primary_key=True),
        sa.Column("tenant_id", postgresql.UUID(as_uuid=True), nullable=False, index=True),
        sa.Column("recipient_id", UUID(as_uuid=True), nullable=True, index=True),
        sa.Column("recipient_email", String(320), nullable=True),
        sa.Column("channel", String(32), nullable=False, index=True),
        sa.Column("template_key", String(128), nullable=False),
        sa.Column("subject", String(512), nullable=True),
        sa.Column("body", Text, nullable=False),
        sa.Column("status", String(32), nullable=False, index=True),
        sa.Column("sent_at", DateTime(timezone=True), nullable=True),
        sa.Column("payload_meta", JSON, nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("deleted_at", sa.DateTime(timezone=True), nullable=True, index=True),
    )
    op.create_table(
        "webhooks",
        sa.Column("id", postgresql.UUID(as_uuid=True), primary_key=True),
        sa.Column("tenant_id", postgresql.UUID(as_uuid=True), nullable=False, index=True),
        sa.Column("name", String(128), nullable=False),
        sa.Column("url", String(2048), nullable=False),
        sa.Column("secret", String(255), nullable=False),
        sa.Column("event_types", JSON, nullable=False),
        sa.Column("is_active", Boolean, nullable=False),
        sa.Column("failure_count", Integer, nullable=False),
        sa.Column("last_triggered_at", DateTime(timezone=True), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("deleted_at", sa.DateTime(timezone=True), nullable=True, index=True),
    )
    op.create_table(
        "audit_logs",
        sa.Column("id", postgresql.UUID(as_uuid=True), primary_key=True),
        sa.Column("tenant_id", postgresql.UUID(as_uuid=True), nullable=False, index=True),
        sa.Column("actor_id", UUID(as_uuid=True), nullable=True, index=True),
        sa.Column("action", String(64), nullable=False, index=True),
        sa.Column("resource_type", String(64), nullable=False, index=True),
        sa.Column("resource_id", UUID(as_uuid=True), nullable=True, index=True),
        sa.Column("changes", JSON, nullable=True),
        sa.Column("ip_address", String(45), nullable=True),
        sa.Column("user_agent", String(512), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
    )


def downgrade() -> None:
    for table in [
        "audit_logs",
        "webhooks",
        "notifications",
        "equipment",
        "service_contracts",
        "sla_breaches",
        "sla_policies",
        "payments",
        "invoice_line_items",
        "invoices",
        "parts_requests",
        "stock_movements",
        "inventory_locations",
        "inventory_items",
        "dispatches",
        "schedules",
        "technician_skills",
        "technicians",
        "work_order_tasks",
        "work_orders",
        "contacts",
        "customer_sites",
        "customers",
        "roles",
        "users",
        "tenants",
    ]:
        op.drop_table(table)
